// ---------------------------------------------------------------------------
// Glossário do Concurseiro — CPPEM
//
// Conteúdo estático: são termos institucionais e de concurso, que mudam pouco.
// Buscar isto no Notion a cada request só adicionaria latência a uma página que
// é essencialmente um documento.
//
// Gerado a partir do markdown fornecido pela equipe. Ao acrescentar termos,
// mantenha a ordem alfabética dentro da letra — a UI não reordena.
// ---------------------------------------------------------------------------

export type GlossaryEntry = {
	term: string;
	definition: string;
};

export type GlossarySection = {
	letter: string;
	entries: readonly GlossaryEntry[];
};

/** Termos técnicos, agrupados por letra inicial. */
export const glossarySections: readonly GlossarySection[] = [
	{
		letter: "A",
		entries: [
			{ term: "Abertura de concurso", definition: "Momento em que o órgão público confirma oficialmente que realizará um concurso." },
			{ term: "Abono de questão", definition: "Situação em que a banca atribui a pontuação de uma questão a todos os candidatos." },
			{ term: "Acertos", definition: "Quantidade de questões respondidas corretamente pelo candidato." },
			{ term: "Acompanhamento pedagógico", definition: "Orientação contínua para analisar a evolução, as dificuldades, o desempenho e a execução do planejamento do aluno." },
			{ term: "Administração Pública", definition: "Conjunto de órgãos, entidades e agentes responsáveis por executar as atividades do Estado." },
			{ term: "Aluno avançado", definition: "Candidato que já possui uma base consolidada e precisa aprofundar conteúdos, revisar e aumentar o volume de questões." },
			{ term: "Aluno iniciante", definition: "Candidato que está começando a preparação e ainda precisa construir uma base nas principais disciplinas." },
			{ term: "Análise de desempenho", definition: "Avaliação dos resultados obtidos pelo aluno em questões, simulados, redações, revisões e metas de estudo." },
			{ term: "Anulação de questão", definition: "Cancelamento de uma questão pela banca. Normalmente, a pontuação é atribuída a todos os candidatos." },
			{ term: "Apostila", definition: "Material didático organizado por disciplina ou concurso, contendo teoria, exemplos, exercícios e orientações." },
			{ term: "Aprova Psico", definition: "Preparação do CPPEM voltada para a etapa de avaliação psicológica dos concursos." },
			{ term: "Aprovação", definition: "Resultado alcançado quando o candidato obtém desempenho suficiente para avançar ou ser classificado no concurso." },
			{ term: "Aprovação dentro das vagas", definition: "Situação em que o candidato fica classificado dentro do número de vagas imediatas previsto no edital." },
			{ term: "Aprovação fora das vagas", definition: "Situação em que o candidato atinge a nota necessária, mas fica além da quantidade inicial de vagas." },
			{ term: "Aprovado", definition: "Candidato que alcançou a pontuação ou os requisitos exigidos em determinada etapa do concurso." },
			{ term: "Aptidão", definition: "Condição do candidato considerado capaz de prosseguir após uma avaliação física, médica, psicológica ou documental." },
			{ term: "Aulão", definition: "Aula especial, normalmente mais longa, voltada para revisão, resolução de questões ou preparação intensiva." },
			{ term: "Aulão de véspera", definition: "Evento realizado próximo à prova para revisar os assuntos mais importantes e apresentar orientações finais." },
			{ term: "Aula ao vivo", definition: "Aula transmitida em tempo real, permitindo a participação ou interação dos alunos." },
			{ term: "Aula gravada", definition: "Aula previamente registrada e disponibilizada para o aluno assistir no horário que desejar." },
			{ term: "Aula inaugural", definition: "Primeira aula de uma turma ou curso, geralmente utilizada para apresentar professores, metodologia e planejamento." },
			{ term: "Atualização do curso", definition: "Inclusão, substituição ou correção de aulas e materiais para adequar o curso ao edital vigente." },
		],
	},
	{
		letter: "B",
		entries: [
			{ term: "Banca examinadora", definition: "Instituição responsável por organizar o concurso, elaborar as provas, divulgar resultados e analisar recursos." },
			{ term: "Banco de questões", definition: "Conjunto organizado de questões utilizado para treinos, simulados, revisões e avaliações." },
			{ term: "Bater com o edital", definition: "Expressão utilizada quando uma aula, matéria ou conteúdo corresponde exatamente ao que está previsto no edital." },
			{ term: "Bater a meta", definition: "Concluir a quantidade de atividades planejadas para o dia ou para a semana." },
			{ term: "Bizu", definition: "Informação curta, estratégica e fácil de memorizar sobre um conteúdo importante para a prova." },
			{ term: "Bloco de estudos", definition: "Período reservado para estudar uma disciplina ou executar uma atividade específica." },
			{ term: "Bloco de questões", definition: "Conjunto de questões selecionadas para treinamento de determinado assunto ou disciplina." },
			{ term: "Boletim de desempenho", definition: "Documento ou relatório que apresenta notas, acertos, erros, classificação ou evolução do candidato." },
			{ term: "Bonificação", definition: "Pontuação adicional concedida em situações previstas no edital." },
		],
	},
	{
		letter: "C",
		entries: [
			{ term: "Caderno bizurado", definition: "Material resumido com conceitos, macetes, esquemas e pontos importantes para revisão rápida." },
			{ term: "Caderno de erros", definition: "Registro das questões erradas, dúvidas, motivos dos erros e conteúdos que precisam ser revisados." },
			{ term: "Caderno de questões", definition: "Material composto por questões organizadas por disciplina, assunto, banca ou concurso." },
			{ term: "Caderno de redação", definition: "Material destinado ao estudo, treinamento e correção de textos discursivos." },
			{ term: "Cadastro de reserva", definition: "Relação de candidatos aprovados além das vagas imediatas, que podem ser convocados durante a validade do concurso." },
			{ term: "Cargo", definition: "Função pública que o candidato pretende ocupar após a aprovação e a nomeação." },
			{ term: "Carreira administrativa", definition: "Área de concursos voltada para cargos administrativos em órgãos públicos, tribunais, autarquias e instituições." },
			{ term: "Carreira policial", definition: "Área de concursos destinada a órgãos de segurança pública, como PM, PC, PF, PRF e Polícia Penal." },
			{ term: "Cartão-resposta", definition: "Documento oficial no qual o candidato marca as respostas da prova objetiva." },
			{ term: "Classificação", definition: "Posição ocupada pelo candidato em relação aos demais concorrentes." },
			{ term: "Cláusula de barreira", definition: "Regra que limita a quantidade de candidatos autorizados a seguir para as próximas etapas." },
			{ term: "Comando da questão", definition: "Parte do enunciado que determina exatamente o que o candidato deve responder, marcar ou julgar." },
			{ term: "Comissão do concurso", definition: "Grupo responsável por acompanhar, fiscalizar e tomar decisões administrativas relacionadas ao certame." },
			{ term: "Conhecimentos básicos", definition: "Disciplinas gerais cobradas para vários cargos, como Português, Informática e Raciocínio Lógico." },
			{ term: "Conhecimentos específicos", definition: "Disciplinas diretamente relacionadas às atribuições e à área do cargo." },
			{ term: "Concurseiro", definition: "Pessoa que estuda e se prepara para concursos públicos." },
			{ term: "Concurso aberto", definition: "Concurso cujo edital já foi publicado e que está com inscrições abertas ou em andamento." },
			{ term: "Concurso autorizado", definition: "Concurso que recebeu autorização administrativa, mas ainda pode não ter banca contratada ou edital publicado." },
			{ term: "Concurso homologado", definition: "Concurso cujo resultado final foi oficialmente confirmado pela Administração Pública." },
			{ term: "Concurso previsto", definition: "Concurso que possui expectativa ou planejamento, mas ainda não foi oficialmente autorizado." },
			{ term: "Concurso público", definition: "Processo seletivo utilizado pelo poder público para escolher candidatos para cargos ou empregos públicos." },
			{ term: "Constância", definition: "Capacidade de manter uma rotina de estudos de maneira regular, mesmo quando a motivação diminui." },
			{ term: "Conteúdo líquido", definition: "Conteúdo efetivamente estudado e compreendido, sem considerar pausas e interrupções." },
			{ term: "Conteúdo programático", definition: "Relação de disciplinas, assuntos e tópicos que podem ser cobrados na prova." },
			{ term: "Contracapa", definition: "Página posterior à capa de um material didático, utilizada para informações institucionais ou apresentação." },
			{ term: "Convocação", definition: "Chamamento oficial para que o candidato participe de uma etapa ou apresente documentos." },
			{ term: "Corpo docente", definition: "Conjunto de professores que ministra aulas em um curso ou instituição." },
			{ term: "Correção comentada", definition: "Explicação detalhada sobre a resposta correta e os motivos pelos quais as demais alternativas estão erradas." },
			{ term: "Corte", definition: "Pontuação ou classificação mínima necessária para permanecer no concurso ou avançar de fase." },
			{ term: "Cronograma", definition: "Organização das atividades de estudo, aulas, revisões, questões e simulados ao longo de determinado período." },
			{ term: "Cronograma individualizado", definition: "Planejamento criado de acordo com a disponibilidade, o nível, as dificuldades e o objetivo específico do aluno." },
			{ term: "Cronograma pós-edital", definition: "Planejamento intensivo elaborado após a publicação do edital." },
			{ term: "Cronograma pré-edital", definition: "Planejamento realizado antes da publicação do edital, com foco na construção de base." },
			{ term: "Cupom", definition: "Código utilizado para aplicar desconto na compra de um curso, plano ou material." },
			{ term: "Curso de formação", definition: "Etapa em que os candidatos aprovados recebem treinamento teórico e prático para exercer o cargo." },
			{ term: "Curso extensivo", definition: "Curso com duração mais longa, voltado para preparação completa e construção de base." },
			{ term: "Curso intensivo", definition: "Curso de menor duração e maior concentração de conteúdos, geralmente direcionado à reta final." },
			{ term: "Curso online", definition: "Preparação realizada por meio de plataforma digital, com aulas, PDFs, questões e outros recursos." },
			{ term: "Curso presencial", definition: "Preparação realizada fisicamente em sala de aula, com contato direto entre alunos e professores." },
			{ term: "Curso regular", definition: "Curso que segue uma programação contínua, sem estar necessariamente vinculado a um edital publicado." },
		],
	},
	{
		letter: "D",
		entries: [
			{ term: "Decoreba", definition: "Memorização realizada sem compreensão aprofundada do conteúdo." },
			{ term: "Decreto", definition: "Ato normativo expedido pelo Poder Executivo para regulamentar uma lei ou tratar de matérias administrativas." },
			{ term: "Desempenho", definition: "Resultado apresentado pelo aluno em atividades, questões, simulados, redações ou provas." },
			{ term: "Diário Oficial", definition: "Meio oficial utilizado para publicar autorizações, editais, nomeações e resultados." },
			{ term: "Didática", definition: "Maneira como o professor organiza e explica o conteúdo para facilitar a aprendizagem." },
			{ term: "Direito Administrativo", definition: "Disciplina que estuda a Administração Pública, seus agentes, atos, poderes, serviços e responsabilidades." },
			{ term: "Direito Constitucional", definition: "Disciplina que estuda a Constituição, os direitos fundamentais e a organização do Estado." },
			{ term: "Direito Penal", definition: "Disciplina que estuda crimes, penas, princípios penais e responsabilidade criminal." },
			{ term: "Direito Processual Penal", definition: "Disciplina que estuda as regras e os procedimentos aplicáveis à investigação e ao processo criminal." },
			{ term: "Direitos Humanos", definition: "Disciplina relacionada à proteção da dignidade, das liberdades e dos direitos fundamentais." },
			{ term: "Disciplina", definition: "Matéria que faz parte do conteúdo programático do concurso." },
			{ term: "Disciplina prioritária", definition: "Matéria que deve receber maior atenção devido ao peso, quantidade de questões, dificuldade ou desempenho do aluno." },
			{ term: "Discursiva", definition: "Prova ou questão em que o candidato precisa produzir uma resposta escrita." },
			{ term: "Distrator", definition: "Alternativa incorreta construída para confundir o candidato em uma questão objetiva." },
		],
	},
	{
		letter: "E",
		entries: [
			{ term: "Edital", definition: "Documento oficial que contém todas as regras do concurso." },
			{ term: "Edital de abertura", definition: "Principal documento do concurso, que apresenta oficialmente suas regras." },
			{ term: "Edital de convocação", definition: "Documento que chama candidatos para uma prova, etapa ou entrega de documentos." },
			{ term: "Edital retificado", definition: "Edital que sofreu alteração ou correção após a publicação original." },
			{ term: "Edital verticalizado", definition: "Conteúdo programático reorganizado em tópicos detalhados para controlar estudo, revisão e questões." },
			{ term: "Eliminado", definition: "Candidato que deixou de cumprir uma regra ou não alcançou o resultado mínimo exigido." },
			{ term: "Embasamento", definition: "Fundamentação utilizada para justificar uma resposta, recurso ou argumento." },
			{ term: "Enunciado", definition: "Texto que apresenta a situação, informação ou pergunta de uma questão." },
			{ term: "Erro de conteúdo", definition: "Erro causado pela falta de conhecimento ou compreensão do assunto." },
			{ term: "Erro de interpretação", definition: "Erro causado pela leitura ou compreensão incorreta do enunciado." },
			{ term: "Erro de marcação", definition: "Erro ocorrido ao transferir ou assinalar a resposta no cartão-resposta." },
			{ term: "Erro por desatenção", definition: "Erro causado por pressa, distração ou falta de leitura cuidadosa." },
			{ term: "Estabilidade", definition: "Proteção funcional adquirida pelo servidor público efetivo após cumprir os requisitos legais." },
			{ term: "Estatuto", definition: "Conjunto de normas que disciplina direitos, deveres, situações e regras de determinada carreira." },
			{ term: "Estudo ativo", definition: "Método em que o aluno participa por meio de questões, explicações, resumos e recuperação do conteúdo." },
			{ term: "Estudo passivo", definition: "Método baseado principalmente em assistir aulas ou ler sem realizar atividades práticas." },
			{ term: "Etapa", definition: "Cada fase que compõe o concurso, como prova objetiva, TAF ou avaliação médica." },
			{ term: "Excedente", definition: "Candidato aprovado além do número de vagas inicialmente oferecido." },
			{ term: "Exercício", definition: "Início efetivo das atividades do servidor após a posse." },
		],
	},
	{
		letter: "F",
		entries: [
			{ term: "Faixa de corte", definition: "Intervalo estimado de pontuação necessário para alcançar uma classificação competitiva." },
			{ term: "Farda", definition: "Uniforme das instituições policiais ou militares e símbolo do objetivo profissional do aluno." },
			{ term: "Fase", definition: "Parte do concurso que possui avaliação ou requisito próprio." },
			{ term: "Feedback", definition: "Retorno dado ao aluno sobre erros, acertos, desempenho e pontos de melhoria." },
			{ term: "Ficha de acompanhamento", definition: "Registro utilizado para acompanhar metas, atividades, dificuldades e evolução do aluno." },
			{ term: "Fichamento", definition: "Registro resumido e organizado das principais informações de uma aula, livro ou PDF." },
			{ term: "Filtro de questões", definition: "Seleção de questões por banca, disciplina, assunto, cargo, nível ou período." },
			{ term: "Folha de avaliação", definition: "Página inserida nos materiais para que o aluno avalie o conteúdo ou a plataforma." },
			{ term: "Formação de base", definition: "Período inicial em que o candidato estuda os fundamentos das principais disciplinas." },
		],
	},
	{
		letter: "G",
		entries: [
			{ term: "Gabarito", definition: "Relação das respostas consideradas corretas pela banca ou pelo professor." },
			{ term: "Gabarito definitivo", definition: "Versão final das respostas após a análise dos recursos." },
			{ term: "Gabarito extraoficial", definition: "Correção produzida por professores ou cursos antes da divulgação oficial da banca." },
			{ term: "Gabarito preliminar", definition: "Primeira versão divulgada pela banca, ainda sujeita a recursos." },
			{ term: "Gargalo", definition: "Principal dificuldade que limita a evolução do aluno." },
			{ term: "Grupo VIP", definition: "Grupo exclusivo de comunicação e apoio destinado a determinados alunos ou planos." },
		],
	},
	{
		letter: "H",
		entries: [
			{ term: "Homologação", definition: "Ato que confirma oficialmente o resultado final do concurso." },
			{ term: "Horas brutas", definition: "Tempo total reservado para estudar, incluindo pausas e interrupções." },
			{ term: "Horas líquidas", definition: "Tempo efetivamente dedicado ao estudo, excluindo pausas e distrações." },
		],
	},
	{
		letter: "I",
		entries: [
			{ term: "Impugnação do edital", definition: "Pedido formal para corrigir ou questionar uma regra considerada irregular no edital." },
			{ term: "Inaptidão", definition: "Resultado atribuído ao candidato que não atende aos critérios de determinada etapa." },
			{ term: "Indeferimento", definition: "Rejeição de uma inscrição, solicitação, recurso, documento ou pedido." },
			{ term: "Índice de acertos", definition: "Percentual de questões respondidas corretamente pelo aluno." },
			{ term: "Índice de erros", definition: "Percentual de questões respondidas incorretamente pelo aluno." },
			{ term: "Informática", definition: "Disciplina que aborda sistemas operacionais, internet, segurança da informação e outros recursos tecnológicos." },
			{ term: "Inscrição", definition: "Procedimento pelo qual o candidato registra sua participação no concurso." },
			{ term: "Inscrição deferida", definition: "Inscrição aceita pela banca organizadora." },
			{ term: "Inscrição indeferida", definition: "Inscrição recusada por alguma irregularidade ou falta de requisito." },
			{ term: "Investigação social", definition: "Etapa que analisa a conduta, os antecedentes e a vida social do candidato." },
			{ term: "Isenção", definition: "Dispensa do pagamento da taxa de inscrição para candidatos que atendam aos critérios do edital." },
			{ term: "Item", definition: "Afirmação ou pergunta individual que deve ser julgada ou respondida pelo candidato." },
		],
	},
	{
		letter: "J",
		entries: [
			{ term: "Jornada de estudos", definition: "Caminho percorrido pelo candidato desde o início da preparação até a aprovação." },
			{ term: "Jurisprudência", definition: "Conjunto de entendimentos e decisões adotados pelos tribunais sobre determinado tema." },
		],
	},
	{
		letter: "L",
		entries: [
			{ term: "Lei seca", definition: "Texto literal da legislação, estudado diretamente, sem comentários doutrinários." },
			{ term: "Legislação especial", definition: "Conjunto de leis específicas cobradas no concurso." },
			{ term: "Legislação estadual", definition: "Normas próprias de determinado estado, frequentemente cobradas em concursos estaduais." },
			{ term: "Legislação institucional", definition: "Normas que tratam da estrutura, dos deveres e do funcionamento da instituição." },
			{ term: "Leitura direcionada", definition: "Leitura realizada com objetivo definido, priorizando os pontos mais relevantes para a prova." },
			{ term: "Lista de aprovados", definition: "Relação oficial dos candidatos aprovados." },
			{ term: "Live", definition: "Transmissão ao vivo utilizada para aulas, mentorias, revisões ou eventos." },
			{ term: "Lotação", definition: "Local, unidade ou setor onde o servidor exercerá suas funções." },
		],
	},
	{
		letter: "M",
		entries: [
			{ term: "Macete", definition: "Forma simplificada de memorizar uma regra, sequência ou informação." },
			{ term: "Mapa mental", definition: "Representação visual que organiza um conteúdo por meio de palavras-chave e conexões." },
			{ term: "Marcação de lei seca", definition: "Técnica de destacar palavras, exceções, prazos e informações importantes no texto legal." },
			{ term: "Material atualizado", definition: "Conteúdo adequado ao edital, à legislação e aos entendimentos vigentes." },
			{ term: "Material de apoio", definition: "PDF, resumo, slide ou lista de questões utilizado junto à aula." },
			{ term: "Material digital", definition: "Conteúdo disponibilizado eletronicamente." },
			{ term: "Material físico", definition: "Apostila, caderno, livro ou outro material impresso." },
			{ term: "Matéria", definition: "Disciplina ou área de conhecimento cobrada no concurso." },
			{ term: "MDT", definition: "Método disponibilizado pelo CPPEM dentro de determinados Planos de Combate." },
			{ term: "Meta diária", definition: "Quantidade de atividades que o aluno precisa executar em um dia." },
			{ term: "Meta mínima", definition: "Atividade reduzida que deve ser cumprida nos dias difíceis para preservar a constância." },
			{ term: "Meta semanal", definition: "Resultado definido para a semana, como horas líquidas, questões ou revisões." },
			{ term: "Mentor", definition: "Profissional que orienta o aluno na organização, estratégia e execução da preparação." },
			{ term: "Mentoria", definition: "Encontro de orientação sobre planejamento, método, desempenho e dificuldades." },
			{ term: "Metodologia", definition: "Conjunto de estratégias e procedimentos utilizados para organizar a aprendizagem." },
			{ term: "Método de estudo", definition: "Forma estruturada de estudar, revisar, praticar e acompanhar resultados." },
			{ term: "Módulo", definition: "Divisão de um curso que reúne aulas e materiais relacionados a uma disciplina ou tema." },
		],
	},
	{
		letter: "N",
		entries: [
			{ term: "Nomeação", definition: "Ato oficial que designa o candidato aprovado para ocupar um cargo público." },
			{ term: "Nota de corte", definition: "Menor pontuação alcançada pelo último candidato classificado dentro de determinado limite." },
			{ term: "Nota final", definition: "Resultado obtido após a aplicação dos critérios, pesos e etapas previstos no edital." },
			{ term: "Nota mínima", definition: "Pontuação mínima exigida para que o candidato não seja eliminado." },
		],
	},
	{
		letter: "O",
		entries: [
			{ term: "Objetividade", definition: "Apresentação direta do conteúdo, com foco no que realmente importa para a prova." },
			{ term: "OBS Studio", definition: "Programa utilizado pelo CPPEM para gravações, aulas, podcasts e transmissões online." },
			{ term: "OP", definition: "Sigla utilizada internamente nos Planos de Combate Tático e Operacional." },
			{ term: "Ordem de classificação", definition: "Sequência dos candidatos de acordo com a pontuação e os critérios de desempate." },
			{ term: "Órgão", definition: "Instituição pública responsável pelo cargo ou pelo concurso." },
			{ term: "Organizadora", definition: "Outro nome utilizado para a banca responsável pelo concurso." },
		],
	},
	{
		letter: "P",
		entries: [
			{ term: "Padrão CPPEM", definition: "Conjunto de orientações visuais, pedagógicas e institucionais dos materiais, aulas e produtos." },
			{ term: "PandaVideo", definition: "Plataforma utilizada para armazenar e organizar os vídeos das aulas do CPPEM." },
			{ term: "PDF", definition: "Formato de arquivo utilizado para disponibilizar apostilas, resumos, leis secas e materiais de apoio." },
			{ term: "PDF de apoio", definition: "Material complementar disponibilizado quando a aula ainda não está disponível ou precisa de suporte escrito." },
			{ term: "Perfil da banca", definition: "Características recorrentes da organizadora, como estilo de cobrança e nível de dificuldade." },
			{ term: "Período de validade", definition: "Prazo durante o qual o concurso pode realizar nomeações." },
			{ term: "Planejamento de estudos", definition: "Organização das disciplinas, atividades, metas e horários de preparação." },
			{ term: "Plano de ação", definition: "Conjunto de tarefas práticas que devem ser executadas para alcançar um objetivo." },
			{ term: "Plano de Combate", definition: "Produto de acompanhamento e preparação do CPPEM, com diferentes modalidades e níveis de suporte." },
			{ term: "Plano de Combate Operacional", definition: "Modalidade com cronogramas, metas, relatórios, ranking e grupo de apoio, sem mentorias ao vivo." },
			{ term: "Plano de Combate Supremo", definition: "Modalidade com mentorias semanais, cursos, cronogramas personalizados, metas, questões e relatórios." },
			{ term: "Plano de Combate Tático", definition: "Modalidade com mentorias mensais, acesso aos cursos, aulas e materiais didáticos." },
			{ term: "Plano de estudos", definition: "Documento que define o que, quando e como o aluno deve estudar." },
			{ term: "Plataforma", definition: "Ambiente digital utilizado para disponibilizar aulas, materiais, cronogramas e questões." },
			{ term: "Pós-edital", definition: "Período iniciado após a publicação do edital." },
			{ term: "Posse", definition: "Ato formal pelo qual o candidato nomeado aceita o cargo público." },
			{ term: "Pré-edital", definition: "Período anterior à publicação do edital, utilizado para construir uma preparação antecipada." },
			{ term: "Preparação direcionada", definition: "Estudo organizado especificamente para uma banca, cargo ou concurso." },
			{ term: "Preparação física", definition: "Treinamento destinado ao desenvolvimento das capacidades exigidas no TAF." },
			{ term: "Previsão de concurso", definition: "Informação de que o concurso poderá ocorrer, ainda sem confirmação de todas as etapas." },
			{ term: "Prioridade", definition: "Grau de importância atribuído a uma disciplina ou atividade." },
			{ term: "Procrastinação", definition: "Adiamento repetido das atividades que deveriam ser executadas." },
			{ term: "Professor", definition: "Profissional responsável por ensinar e explicar o conteúdo da disciplina." },
			{ term: "Programa de estudos", definition: "Organização dos conteúdos e atividades trabalhados durante a preparação." },
			{ term: "Prova de títulos", definition: "Etapa em que são avaliadas formações acadêmicas, cursos ou experiências." },
			{ term: "Prova discursiva", definition: "Avaliação escrita em que o candidato desenvolve uma resposta ou texto fundamentado." },
			{ term: "Prova objetiva", definition: "Avaliação composta por questões de múltipla escolha ou itens de certo e errado." },
			{ term: "Prova social", definition: "Demonstração de resultados por meio de aprovados, depoimentos e classificações." },
			{ term: "Provimento", definition: "Ato de preenchimento de um cargo público." },
			{ term: "Psicotécnico", definition: "Nome popular da avaliação psicológica aplicada em concursos." },
		],
	},
	{
		letter: "Q",
		entries: [
			{ term: "QConcursos", definition: "Plataforma utilizada para pesquisar, filtrar e resolver questões de concursos." },
			{ term: "Questão anulada", definition: "Questão cancelada pela banca devido a erro ou problema identificado." },
			{ term: "Questão comentada", definition: "Questão acompanhada de explicação sobre o conteúdo e a resposta correta." },
			{ term: "Questão de certo ou errado", definition: "Item em que o candidato julga uma afirmação como correta ou incorreta." },
			{ term: "Questão inédita", definition: "Questão criada especialmente para determinado material ou treinamento." },
			{ term: "Questão objetiva", definition: "Questão que apresenta alternativas ou opções de resposta previamente definidas." },
			{ term: "Questão oficial", definition: "Questão efetivamente aplicada por uma banca em concurso anterior." },
			{ term: "Questão passível de recurso", definition: "Questão que apresenta possível erro, ambiguidade ou desconformidade com o edital." },
			{ term: "Questões pré-selecionadas", definition: "Questões escolhidas de acordo com a banca, disciplina, assunto ou objetivo do aluno." },
		],
	},
	{
		letter: "R",
		entries: [
			{ term: "Raciocínio Lógico", definition: "Disciplina que envolve estruturas lógicas, proposições, argumentos e problemas matemáticos." },
			{ term: "Raio-X do edital", definition: "Análise detalhada do edital, destacando conteúdos, etapas, exigências e prioridades." },
			{ term: "Ranking", definition: "Classificação dos alunos conforme horas estudadas, questões, simulados ou desempenho." },
			{ term: "Recurso", definition: "Pedido formal apresentado para contestar uma questão, gabarito, resultado ou decisão da banca." },
			{ term: "Redação", definition: "Texto produzido pelo candidato de acordo com o tema e as regras da prova." },
			{ term: "Redação dissertativo-argumentativa", definition: "Texto em que o candidato apresenta uma tese e utiliza argumentos para defendê-la." },
			{ term: "Redação discursiva", definition: "Avaliação escrita que exige desenvolvimento textual ou resposta fundamentada." },
			{ term: "Reforço", definition: "Atividade ou aula adicional destinada a trabalhar dificuldades específicas." },
			{ term: "Regra de recuperação", definition: "Estratégia para reorganizar atividades não cumpridas sem sobrecarregar os dias seguintes." },
			{ term: "Relatório de evolução", definition: "Documento que apresenta resultados, progresso, dificuldades e pontos de melhoria do aluno." },
			{ term: "Relatório semanal", definition: "Registro periódico das atividades realizadas e do desempenho obtido durante a semana." },
			{ term: "Requisito", definition: "Condição que o candidato deve cumprir para participar ou tomar posse no cargo." },
			{ term: "Reserva de vagas", definition: "Separação de parte das vagas para candidatos que atendem aos critérios previstos em lei." },
			{ term: "Resolução de questões", definition: "Prática de responder questões para consolidar conteúdos e conhecer o perfil da banca." },
			{ term: "Resumo", definition: "Material sintetizado com os principais pontos de determinado conteúdo." },
			{ term: "Reta final", definition: "Período próximo à prova, com aumento de revisões, questões e simulados." },
			{ term: "Retificação", definition: "Alteração ou correção oficial realizada em um edital ou documento do concurso." },
			{ term: "Revisão", definition: "Retomada planejada de um conteúdo estudado anteriormente." },
			{ term: "Revisão de 24 horas", definition: "Revisão realizada aproximadamente um dia depois do primeiro estudo." },
			{ term: "Revisão de 7 dias", definition: "Revisão realizada aproximadamente uma semana após o estudo inicial." },
			{ term: "Revisão de 30 dias", definition: "Revisão realizada aproximadamente um mês depois do estudo inicial." },
			{ term: "Revisão cumulativa", definition: "Revisão que reúne conteúdos estudados em diferentes períodos." },
			{ term: "Revisão de véspera", definition: "Retomada rápida dos pontos mais importantes realizada pouco antes da prova." },
			{ term: "Revisão espaçada", definition: "Técnica que distribui as revisões ao longo do tempo para aumentar a retenção." },
			{ term: "RLM", definition: "Sigla de Raciocínio Lógico-Matemático." },
			{ term: "Rodízio de matérias", definition: "Alternância organizada entre diferentes disciplinas durante a semana ou ciclo." },
			{ term: "Rumo ao TAF", definition: "Preparação do CPPEM voltada ao Teste de Aptidão Física." },
		],
	},
	{
		letter: "S",
		entries: [
			{ term: "Simulado", definition: "Prova de treinamento elaborada para reproduzir condições e conteúdos do concurso." },
			{ term: "Simulado comentado", definition: "Simulado cuja correção é acompanhada de explicações dos professores." },
			{ term: "Simulado diagnóstico", definition: "Avaliação aplicada para identificar o nível atual e as dificuldades do aluno." },
			{ term: "Simulado presencial", definition: "Simulado aplicado fisicamente, com condições próximas às da prova." },
			{ term: "Source", definition: "Fonte ou arquivo original do vídeo utilizado para publicar a aula na plataforma." },
			{ term: "Suporte", definition: "Atendimento destinado a resolver dúvidas técnicas, pedagógicas ou administrativas." },
		],
	},
	{
		letter: "T",
		entries: [
			{ term: "TAF", definition: "Teste de Aptidão Física utilizado para avaliar o desempenho físico exigido pelo concurso." },
			{ term: "Taxa de inscrição", definition: "Valor pago para confirmar a participação no concurso." },
			{ term: "Teoria", definition: "Parte do estudo destinada à compreensão dos conceitos, regras e fundamentos." },
			{ term: "Termo de posse", definition: "Documento formal assinado pelo candidato ao assumir o cargo." },
			{ term: "Tópico", definition: "Divisão específica de um conteúdo dentro de uma disciplina." },
			{ term: "Tutory", definition: "Plataforma utilizada pelo CPPEM para organizar alunos, aulas, cronogramas, metas e Planos de Combate." },
			{ term: "Turma avançada", definition: "Turma destinada a alunos com maior tempo de preparação ou que precisam de aprofundamento." },
			{ term: "Turma de base", definition: "Turma destinada à construção dos conhecimentos fundamentais." },
			{ term: "Turma online", definition: "Grupo de alunos que acompanha as aulas por meio de plataforma digital." },
			{ term: "Turma presencial", definition: "Grupo de alunos que participa das aulas fisicamente na unidade do curso." },
		],
	},
	{
		letter: "V",
		entries: [
			{ term: "Vaga imediata", definition: "Vaga prevista no edital para preenchimento inicial após a conclusão do concurso." },
			{ term: "Vagas previstas", definition: "Quantidade estimada ou anunciada antes da publicação oficial do edital." },
			{ term: "Validade do concurso", definition: "Período em que o órgão pode convocar e nomear os candidatos aprovados." },
			{ term: "Vade Mecum", definition: "Coletânea de leis e normas utilizada como material de consulta e estudo." },
			{ term: "Videoaula", definition: "Aula apresentada em formato de vídeo, ao vivo ou gravada." },
			{ term: "Vídeo baixado", definition: "Arquivo de vídeo obtido por download, diferente da fonte original utilizada na plataforma." },
			{ term: "Visão geral", definition: "Apresentação resumida da estrutura e dos pontos principais de um concurso ou conteúdo." },
		],
	},
];

/**
 * Expressões e jargão próprios do CPPEM.
 *
 * Ficam separadas dos termos técnicos de propósito: não são vocabulário de
 * concurso, e sim a linguagem da casa. Misturar as duas listas confundiria quem
 * chega buscando o significado de "cadastro de reserva".
 */
export const glossaryExpressions: readonly GlossaryEntry[] = [
	{ term: "A farda", definition: "Representação do objetivo final do aluno que busca uma carreira policial." },
	{ term: "Acelerar a aprovação", definition: "Organizar o estudo para eliminar desperdícios e aumentar a eficiência da preparação." },
	{ term: "Aluno combatente", definition: "Forma de se referir ao aluno que participa ativamente da preparação e executa suas metas." },
	{ term: "Banco de questões atualizado", definition: "Conjunto de questões revisado e adequado aos concursos e conteúdos trabalhados." },
	{ term: "Campo de batalha", definition: "Metáfora utilizada para representar os desafios da preparação para concursos." },
	{ term: "Caveira Black", definition: "Plano presencial com aulas, materiais, plano de estudos, simulados, aulões e benefícios específicos." },
	{ term: "Caveira Dourada", definition: "Plano presencial com aulas, materiais, plano de estudos, transmissões ao vivo e benefícios da modalidade." },
	{ term: "Caveira Prata", definition: "Plano presencial com aulas, materiais didáticos, plano de estudos e benefícios correspondentes." },
	{ term: "Combate", definition: "Representação da execução diária do planejamento de estudos." },
	{ term: "Conquistar a farda", definition: "Ser aprovado e ingressar na carreira policial desejada." },
	{ term: "Disciplina antes da motivação", definition: "Princípio de que o candidato deve executar o planejamento mesmo quando não estiver motivado." },
	{ term: "Executar o plano", definition: "Cumprir as atividades previstas no cronograma sem modificações desnecessárias." },
	{ term: "Grupo de combatentes", definition: "Comunidade de alunos que compartilham objetivos, acompanhamento e rotina de estudos." },
	{ term: "Irmandade", definition: "Sentimento de pertencimento e apoio entre alunos que possuem o mesmo objetivo." },
	{ term: "Missão", definition: "Objetivo ou tarefa que deve ser cumprida durante a preparação." },
	{ term: "Nome na lista", definition: "Expressão utilizada para representar a publicação do candidato entre os aprovados." },
	{ term: "Operação aprovação", definition: "Expressão que representa uma preparação organizada, estratégica e direcionada ao resultado." },
	{ term: "Parte pesada", definition: "Organização de cronogramas, metas, revisões e questões estruturada pelo CPPEM." },
	{ term: "Plano de Combate", definition: "Estratégia organizada de preparação, acompanhamento e execução das atividades do aluno." },
	{ term: "Rumo à aprovação", definition: "Expressão motivacional que representa o avanço contínuo em direção ao resultado." },
	{ term: "Seu sonho, nosso objetivo", definition: "Frase institucional que representa o compromisso do CPPEM com a aprovação do aluno." },
	{ term: "Soldado", definition: "Forma motivacional de se referir ao aluno ou futuro integrante de uma carreira militar." },
	{ term: "Sua vez agora", definition: "Expressão utilizada para incentivar o aluno a assumir o protagonismo da preparação." },
	{ term: "Vestir a farda", definition: "Ingressar efetivamente na instituição policial ou militar após a aprovação e formação." },
	{ term: "Quem ensina aqui já passou", definition: "Expressão que reforça a experiência prática dos professores e mentores." },
	{ term: "Quem passa não é o mais inteligente, é o mais dedicado", definition: "Frase que destaca a importância da disciplina, constância e execução." },
];

/** Total de verbetes — usado no herói da página. */
export const glossaryTotal =
	glossarySections.reduce((soma, secao) => soma + secao.entries.length, 0) +
	glossaryExpressions.length;

